export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST"
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS"
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE"

export const BOOK_ADDED_TO_CART = "BOOK_ADDED_TO_CART"
export const BOOK_DELETE_FROM_CART = "BOOK_DELETE_FROM_CART"
export const BOOK_DECREASE_IN_CART = "BOOK_DECREASE_IN_CART"